version: "3.8"

services:
 lab4-db:
  image: postgres
  volumes:
   - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql 
   - lab4-db-volume:/var/lib/postgresql/data
  networks:
    - lab4-db-network
    - lab4-adminer-network
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    POSTGRES_DB: books


 lab4-adminer:
  image: adminer
  ports:
    - 8080:8080
  networks:
    - lab4-adminer-network


 lab4-api:
  build: ./backend
  ports:
    - 5555:80 
  networks:
    - lab4-db-network
  environment:
    PGUSER: admin 
    PGPASSWORD: admin 
    PGDATABASE: books 
    PGHOST: lab4-db 
    PGPORT: 5432


networks:
 lab4-db-network:
 lab4-adminer-network:

volumes:
 lab4-db-volume:
